AWSTemplateFormatVersion: '2010-09-09'
Description: 'Autoscaling group for microservices with Kong, MySQL, and Kafka'

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Type: String
    Default: t3.medium
  AMI:
    Type: AWS::EC2::Image::Id
  MySQLRootPassword:
    Type: String
    NoEcho: true
  MySQLUser:
    Type: String
  MySQLRootUser:
    Type: String
  MySQLPassword:
    Type: String
    NoEcho: true
  KafkaAdvertisedListeners:
    Type: String
    Default: PLAINTEXT://localhost:9092
  KongConfigBucket:
    Type: String
    Description: S3 bucket containing Kong configuration and plugins
  ECSClusterName:
    Type: String
    Description: Name of the ECS Cluster
  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Description: Load Balancer to use while deployment
  PublicLoadBalancerSg:
    Type: AWS::EC2::SecurityGroup
    Description: Load Balancer SG
  VPCCIDR:
    Type: String
    Description: CIDR of VPC

Resources:
  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: myapp.local
      Vpc: !Ref VPC

  KafkaServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: kafka
      NamespaceId: !Ref ServiceDiscoveryNamespace
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300

  MySQLServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: mysql
      NamespaceId: !Ref ServiceDiscoveryNamespace
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300

  KongServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: kong
      NamespaceId: !Ref ServiceDiscoveryNamespace
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecsTaskExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetObject
                Resource: "*"

  KongTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kong-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: kong
          Image: kong:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
            - ContainerPort: 8443
              HostPort: 8443
            - ContainerPort: 8001
              HostPort: 8001
            - ContainerPort: 8444
              HostPort: 8444
          Environment:
            - Name: KONG_DATABASE
              Value: "off"
            - Name: KONG_DECLARATIVE_CONFIG
              Value: "/usr/local/kong/declarative/kong.yml"
            - Name: KONG_PROXY_ACCESS_LOG
              Value: "/dev/stdout"
            - Name: KONG_ADMIN_ACCESS_LOG
              Value: "/dev/stdout"
            - Name: KONG_PROXY_ERROR_LOG
              Value: "/dev/stderr"
            - Name: KONG_ADMIN_ERROR_LOG
              Value: "/dev/stderr"
            - Name: KONG_ADMIN_LISTEN
              Value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          Volumes:
            - Name: kong-config
              Host:
                SourcePath: /app/kong/config
            - Name: custom-plugins
              Host:
                SourcePath: /app/kong/custom-plugins

  MySQLTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: mysql-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: mysql
          Image: mysql:8.3.0
          Essential: true
          Environment:
            - Name: MYSQL_ROOT_PASSWORD
              Value: !Ref MySQLRootPassword
            - Name: MYSQL_USER
              Value: !Ref MySQLUser
            - Name: MYSQL_ROOT_USER
              Value: !Ref MySQLRootUser
            - Name: MYSQL_PASSWORD
              Value: !Ref MySQLPassword
          PortMappings:
            - ContainerPort: 3306
              HostPort: 3306
          Volumes:
            - Name: mysql-data
              Host:
                SourcePath: /data/mysql

  KafkaTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kafka-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: zookeeper
          Image: confluentinc/cp-zookeeper:7.4.4
          Essential: true
          Environment:
            - Name: ZOOKEEPER_CLIENT_PORT
              Value: "2181"
            - Name: ZOOKEEPER_TICK_TIME
              Value: "2000"
          PortMappings:
            - ContainerPort: 2181
              HostPort: 2181
        - Name: kafka
          Image: confluentinc/cp-kafka:7.4.4
          Essential: true
          DependsOn:
            - ContainerName: zookeeper
              Condition: START
          Environment:
            - Name: KAFKA_BROKER_ID
              Value: "1"
            - Name: KAFKA_ZOOKEEPER_CONNECT
              Value: "zookeeper:2181"
            - Name: KAFKA_ADVERTISED_LISTENERS
              Value: !Ref KafkaAdvertisedListeners
            - Name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              Value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - Name: KAFKA_INTER_BROKER_LISTENER_NAME
              Value: "PLAINTEXT"
            - Name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              Value: "1"
          PortMappings:
            - ContainerPort: 9092
              HostPort: 9092

  KongService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref KongTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EC2SecurityGroup]
          Subnets: !Ref PrivateSubnets
      LoadBalancers:
        - TargetGroupArn: !Ref KongTargetGroup
          ContainerName: kong
          ContainerPort: 8000

  MySQLService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref MySQLTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EC2SecurityGroup]
          Subnets: !Ref PrivateSubnets

  LaunchTemplate:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - [!Ref EC2SecurityGroup]

  KafkaService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref KafkaTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EC2SecurityGroup]
          Subnets: !Ref PrivateSubnets

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances
      VpcId: !Ref VPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8000
        ToPort: 8000
        SourceSecurityGroupId: !Ref PublicLoadBalancerSg
      - IpProtocol: tcp
        FromPort: 8443
        ToPort: 8443
        SourceSecurityGroupId: !Ref PublicLoadBalancerSg

      # Restrict MySQL access to internal subnets
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: !Ref VPCCIDR

      # Restrict Kafka and Zookeeper access to internal subnets
      - IpProtocol: tcp
        FromPort: 9092
        ToPort: 9092
        CidrIp: !Ref VPCCIDR
      - IpProtocol: tcp
        FromPort: 2181
        ToPort: 2181
        CidrIp: !Ref VPCCIDR

      # DNS (TCP and UDP) restricted to internal subnets
      - IpProtocol: udp
        FromPort: 53
        ToPort: 53
        CidrIp: !Ref VPCCIDR
      - IpProtocol: tcp
        FromPort: 53
        ToPort: 53
        CidrIp: !Ref VPCCIDR

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PrivateSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300

  # Target Group for Kong
  KongTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Port: 8000
      Protocol: HTTP
      VpcId: !Ref VPC

  # Update ALB Listener
  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - PublicLoadBalancer
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref KongTargetGroup
          Type: 'forward'
      LoadBalancerArn: !Ref PublicLoadBalancer
      Port: 8000
      Protocol: HTTP

Outputs:
  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !Ref AutoScalingGroup
  ServiceDiscoveryNamespace:
    Description: Service Discovery Namespace
    Value: myapp.local
  KafkaServiceEndpoint:
    Description: Kafka Service Endpoint
    Value: kafka.myapp.local
  MySQLServiceEndpoint:
    Description: MySQL Service Endpoint
    Value: mysql.myapp.local
  KongServiceEndpoint:
    Description: Kong Service Endpoint
    Value: kong.myapp.local
