version: '3'
services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql-db:
    driver: local
